name: Java CI

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ“‚
        uses: actions/checkout@v4
      
      - name: Set up JDK 11 âš™ï¸
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '21'
      
      - name: Cache Maven packages â›“ï¸
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build with Maven ğŸ”§
        run: mvn --batch-mode --update-snapshots verify -fae
        
      - name: Deploy ğŸš€
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: releng/com.obeonetwork.mbse.capella.vpx.site/target/repository
          target-folder: nightly
          single-commit: true # Remove history in gh-pages
          clean: true # Remove deprecated files
    
      - name: Get the tag version ğŸ·ï¸
        id: get_version
        run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
  
      - name: Deploy Release ğŸš€ğŸ·ï¸
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: releng/com.obeonetwork.mbse.capella.vpx.site/target/repository
          target-folder: releases/${{ steps.get_version.outputs.TAG_VERSION }}
          single-commit: true # Remove history in gh-pages
          clean: true # Remove deprecated files
